#pragma once
/*
 * Auto-generated by Glaze — DO NOT EDIT.
 * API: gl 3.3 | Language: C++ Handle | Generated: 2026-04-09 07:59:18 UTC
 */

#ifndef __GLAZE_GL_HANDLE_HPP__
#define __GLAZE_GL_HANDLE_HPP__

#include "gl.hpp"

namespace gl {
namespace handle {

/**
 * @brief Object-style wrapper around an OpenGL Buffer handle.
 * Exposes legacy (non-DSA) GL commands that take a Buffer as
 * their first parameter as member methods, returning the strongly-typed
 * wrappers (UniformLocation, std::string, …) where available.
 */
class Buffer {
    ::gl::BufferId m_id;
public:
    Buffer() = default;
    explicit Buffer(::gl::BufferId id) : m_id(id) {}
    ::gl::BufferId id() const { return m_id; }
#if GLAZE_GL_VERSION >= 15
    GLboolean is() const {
        return ::gl::isBuffer(m_id);
    }
#endif
};

/**
 * @brief Object-style wrapper around an OpenGL Framebuffer handle.
 * Exposes legacy (non-DSA) GL commands that take a Framebuffer as
 * their first parameter as member methods, returning the strongly-typed
 * wrappers (UniformLocation, std::string, …) where available.
 */
class Framebuffer {
    ::gl::Framebuffer m_id;
public:
    Framebuffer() = default;
    explicit Framebuffer(::gl::Framebuffer id) : m_id(id) {}
    ::gl::Framebuffer id() const { return m_id; }
#if GLAZE_GL_VERSION >= 30
    GLboolean is() const {
        return ::gl::isFramebuffer(m_id);
    }
#endif
};

/**
 * @brief Object-style wrapper around an OpenGL Program handle.
 * Exposes legacy (non-DSA) GL commands that take a Program as
 * their first parameter as member methods, returning the strongly-typed
 * wrappers (UniformLocation, std::string, …) where available.
 */
class Program {
    ::gl::Program m_id;
public:
    Program() = default;
    explicit Program(::gl::Program id) : m_id(id) {}
    ::gl::Program id() const { return m_id; }
#if GLAZE_GL_VERSION >= 20
    void attachShader(::gl::handle::Shader shader) const {
        return ::gl::attachShader(m_id, shader.id());
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void bindAttribLocation(AttribLocation index, const GLchar * name) const {
        return ::gl::bindAttribLocation(m_id, index, name);
    }
#endif
#if GLAZE_GL_VERSION >= 30
    void bindFragDataLocation(GLuint color, const GLchar * name) const {
        return ::gl::bindFragDataLocation(m_id, color, name);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void bindFragDataLocationIndexed(GLuint colorNumber, GLuint index, const GLchar * name) const {
        return ::gl::bindFragDataLocationIndexed(m_id, colorNumber, index, name);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void delete_() const {
        return ::gl::deleteProgram(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void detachShader(::gl::handle::Shader shader) const {
        return ::gl::detachShader(m_id, shader.id());
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getActiveAttrib(GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, ::gl::AttributeType * type, GLchar * name) const {
        return ::gl::getActiveAttrib(m_id, index, bufSize, length, size, type, name);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    std::string getActiveAttrib(GLuint index, GLsizei bufSize, GLint * size, ::gl::AttributeType * type) const {
        return ::gl::getActiveAttrib(m_id, index, bufSize, size, type);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getActiveUniform(GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, ::gl::UniformType * type, GLchar * name) const {
        return ::gl::getActiveUniform(m_id, index, bufSize, length, size, type, name);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    std::string getActiveUniform(GLuint index, GLsizei bufSize, GLint * size, ::gl::UniformType * type) const {
        return ::gl::getActiveUniform(m_id, index, bufSize, size, type);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    void getActiveUniformBlockName(GLuint uniformBlockIndex, GLsizei bufSize, GLsizei * length, GLchar * uniformBlockName) const {
        return ::gl::getActiveUniformBlockName(m_id, uniformBlockIndex, bufSize, length, uniformBlockName);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    std::string getActiveUniformBlockName(GLuint uniformBlockIndex, GLsizei bufSize) const {
        return ::gl::getActiveUniformBlockName(m_id, uniformBlockIndex, bufSize);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    void getActiveUniformBlockiv(GLuint uniformBlockIndex, ::gl::UniformBlockPName pname, GLint * params) const {
        return ::gl::getActiveUniformBlockiv(m_id, uniformBlockIndex, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    GLint getActiveUniformBlockiv(GLuint uniformBlockIndex, ::gl::UniformBlockPName pname) const {
        return ::gl::getActiveUniformBlockiv(m_id, uniformBlockIndex, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    void getActiveUniformName(GLuint uniformIndex, GLsizei bufSize, GLsizei * length, GLchar * uniformName) const {
        return ::gl::getActiveUniformName(m_id, uniformIndex, bufSize, length, uniformName);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    std::string getActiveUniformName(GLuint uniformIndex, GLsizei bufSize) const {
        return ::gl::getActiveUniformName(m_id, uniformIndex, bufSize);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    void getActiveUniformsiv(GLsizei uniformCount, const GLuint * uniformIndices, ::gl::UniformPName pname, GLint * params) const {
        return ::gl::getActiveUniformsiv(m_id, uniformCount, uniformIndices, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    GLint getActiveUniformsiv(GLsizei uniformCount, const GLuint * uniformIndices, ::gl::UniformPName pname) const {
        return ::gl::getActiveUniformsiv(m_id, uniformCount, uniformIndices, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getAttachedShaders(GLsizei maxCount, GLsizei * count, ::gl::Shader * shaders) const {
        return ::gl::getAttachedShaders(m_id, maxCount, count, shaders);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    AttribLocation getAttribLocation(const GLchar * name) const {
        return ::gl::getAttribLocation(m_id, name);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    UniformLocation getFragDataIndex(const GLchar * name) const {
        return ::gl::getFragDataIndex(m_id, name);
    }
#endif
#if GLAZE_GL_VERSION >= 30
    UniformLocation getFragDataLocation(const GLchar * name) const {
        return ::gl::getFragDataLocation(m_id, name);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getInfoLog(GLsizei bufSize, GLsizei * length, GLchar * infoLog) const {
        return ::gl::getProgramInfoLog(m_id, bufSize, length, infoLog);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    std::string getInfoLog(GLsizei bufSize) const {
        return ::gl::getProgramInfoLog(m_id, bufSize);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    std::string getInfoLog() const {
        return ::gl::getProgramInfoLog(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getiv(::gl::ProgramProperty pname, GLint * params) const {
        return ::gl::getProgramiv(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    GLint getiv(::gl::ProgramProperty pname) const {
        return ::gl::getProgramiv(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 30
    void getTransformFeedbackVarying(GLuint index, GLsizei bufSize, GLsizei * length, GLsizei * size, ::gl::AttributeType * type, GLchar * name) const {
        return ::gl::getTransformFeedbackVarying(m_id, index, bufSize, length, size, type, name);
    }
#endif
#if GLAZE_GL_VERSION >= 30
    std::string getTransformFeedbackVarying(GLuint index, GLsizei bufSize, GLsizei * size, ::gl::AttributeType * type) const {
        return ::gl::getTransformFeedbackVarying(m_id, index, bufSize, size, type);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    GLuint getUniformBlockIndex(const GLchar * uniformBlockName) const {
        return ::gl::getUniformBlockIndex(m_id, uniformBlockName);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    void getUniformIndices(GLsizei uniformCount, const GLchar *const* uniformNames, GLuint * uniformIndices) const {
        return ::gl::getUniformIndices(m_id, uniformCount, uniformNames, uniformIndices);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    GLuint getUniformIndices(GLsizei uniformCount, const GLchar *const* uniformNames) const {
        return ::gl::getUniformIndices(m_id, uniformCount, uniformNames);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    UniformLocation getUniformLocation(const GLchar * name) const {
        return ::gl::getUniformLocation(m_id, name);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getUniformfv(GLint location, GLfloat * params) const {
        return ::gl::getUniformfv(m_id, location, params);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    GLfloat getUniformfv(GLint location) const {
        return ::gl::getUniformfv(m_id, location);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getUniformiv(GLint location, GLint * params) const {
        return ::gl::getUniformiv(m_id, location, params);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    GLint getUniformiv(GLint location) const {
        return ::gl::getUniformiv(m_id, location);
    }
#endif
#if GLAZE_GL_VERSION >= 30
    void getUniformuiv(GLint location, GLuint * params) const {
        return ::gl::getUniformuiv(m_id, location, params);
    }
#endif
#if GLAZE_GL_VERSION >= 30
    GLuint getUniformuiv(GLint location) const {
        return ::gl::getUniformuiv(m_id, location);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    GLboolean is() const {
        return ::gl::isProgram(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void link() const {
        return ::gl::linkProgram(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 30
    void transformFeedbackVaryings(GLsizei count, const GLchar *const* varyings, ::gl::TransformFeedbackBufferMode bufferMode) const {
        return ::gl::transformFeedbackVaryings(m_id, count, varyings, bufferMode);
    }
#endif
#if GLAZE_GL_VERSION >= 31
    void uniformBlockBinding(GLuint uniformBlockIndex, GLuint uniformBlockBinding) const {
        return ::gl::uniformBlockBinding(m_id, uniformBlockIndex, uniformBlockBinding);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void use() const {
        return ::gl::useProgram(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void validate() const {
        return ::gl::validateProgram(m_id);
    }
#endif
};

/**
 * @brief Object-style wrapper around an OpenGL Query handle.
 * Exposes legacy (non-DSA) GL commands that take a Query as
 * their first parameter as member methods, returning the strongly-typed
 * wrappers (UniformLocation, std::string, …) where available.
 */
class Query {
    ::gl::Query m_id;
public:
    Query() = default;
    explicit Query(::gl::Query id) : m_id(id) {}
    ::gl::Query id() const { return m_id; }
#if GLAZE_GL_VERSION >= 33
    void getObjecti64v(::gl::QueryObjectParameterName pname, GLint64 * params) const {
        return ::gl::getQueryObjecti64v(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    GLint64 getObjecti64v(::gl::QueryObjectParameterName pname) const {
        return ::gl::getQueryObjecti64v(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 15
    void getObjectiv(::gl::QueryObjectParameterName pname, GLint * params) const {
        return ::gl::getQueryObjectiv(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 15
    GLint getObjectiv(::gl::QueryObjectParameterName pname) const {
        return ::gl::getQueryObjectiv(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void getObjectui64v(::gl::QueryObjectParameterName pname, GLuint64 * params) const {
        return ::gl::getQueryObjectui64v(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    GLuint64 getObjectui64v(::gl::QueryObjectParameterName pname) const {
        return ::gl::getQueryObjectui64v(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 15
    void getObjectuiv(::gl::QueryObjectParameterName pname, GLuint * params) const {
        return ::gl::getQueryObjectuiv(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 15
    GLuint getObjectuiv(::gl::QueryObjectParameterName pname) const {
        return ::gl::getQueryObjectuiv(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 15
    GLboolean is() const {
        return ::gl::isQuery(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void counter(::gl::QueryCounterTarget target) const {
        return ::gl::queryCounter(m_id, target);
    }
#endif
};

/**
 * @brief Object-style wrapper around an OpenGL Renderbuffer handle.
 * Exposes legacy (non-DSA) GL commands that take a Renderbuffer as
 * their first parameter as member methods, returning the strongly-typed
 * wrappers (UniformLocation, std::string, …) where available.
 */
class Renderbuffer {
    ::gl::Renderbuffer m_id;
public:
    Renderbuffer() = default;
    explicit Renderbuffer(::gl::Renderbuffer id) : m_id(id) {}
    ::gl::Renderbuffer id() const { return m_id; }
#if GLAZE_GL_VERSION >= 30
    GLboolean is() const {
        return ::gl::isRenderbuffer(m_id);
    }
#endif
};

/**
 * @brief Object-style wrapper around an OpenGL Sampler handle.
 * Exposes legacy (non-DSA) GL commands that take a Sampler as
 * their first parameter as member methods, returning the strongly-typed
 * wrappers (UniformLocation, std::string, …) where available.
 */
class Sampler {
    ::gl::Sampler m_id;
public:
    Sampler() = default;
    explicit Sampler(::gl::Sampler id) : m_id(id) {}
    ::gl::Sampler id() const { return m_id; }
#if GLAZE_GL_VERSION >= 33
    void getParameterIiv(::gl::SamplerParameterI pname, GLint * params) const {
        return ::gl::getSamplerParameterIiv(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    GLint getParameterIiv(::gl::SamplerParameterI pname) const {
        return ::gl::getSamplerParameterIiv(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void getParameterIuiv(::gl::SamplerParameterI pname, GLuint * params) const {
        return ::gl::getSamplerParameterIuiv(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    GLuint getParameterIuiv(::gl::SamplerParameterI pname) const {
        return ::gl::getSamplerParameterIuiv(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void getParameterfv(::gl::SamplerParameterF pname, GLfloat * params) const {
        return ::gl::getSamplerParameterfv(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    GLfloat getParameterfv(::gl::SamplerParameterF pname) const {
        return ::gl::getSamplerParameterfv(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void getParameteriv(::gl::SamplerParameterI pname, GLint * params) const {
        return ::gl::getSamplerParameteriv(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    GLint getParameteriv(::gl::SamplerParameterI pname) const {
        return ::gl::getSamplerParameteriv(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    GLboolean is() const {
        return ::gl::isSampler(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void parameterIiv(::gl::SamplerParameterI pname, const GLint * param) const {
        return ::gl::samplerParameterIiv(m_id, pname, param);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void parameterIuiv(::gl::SamplerParameterI pname, const GLuint * param) const {
        return ::gl::samplerParameterIuiv(m_id, pname, param);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void parameterf(::gl::SamplerParameterF pname, GLfloat param) const {
        return ::gl::samplerParameterf(m_id, pname, param);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void parameterfv(::gl::SamplerParameterF pname, const GLfloat * param) const {
        return ::gl::samplerParameterfv(m_id, pname, param);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void parameteri(::gl::SamplerParameterI pname, GLint param) const {
        return ::gl::samplerParameteri(m_id, pname, param);
    }
#endif
#if GLAZE_GL_VERSION >= 33
    void parameteriv(::gl::SamplerParameterI pname, const GLint * param) const {
        return ::gl::samplerParameteriv(m_id, pname, param);
    }
#endif
};

/**
 * @brief Object-style wrapper around an OpenGL Shader handle.
 * Exposes legacy (non-DSA) GL commands that take a Shader as
 * their first parameter as member methods, returning the strongly-typed
 * wrappers (UniformLocation, std::string, …) where available.
 */
class Shader {
    ::gl::Shader m_id;
public:
    Shader() = default;
    explicit Shader(::gl::Shader id) : m_id(id) {}
    ::gl::Shader id() const { return m_id; }
#if GLAZE_GL_VERSION >= 20
    void compile() const {
        return ::gl::compileShader(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void delete_() const {
        return ::gl::deleteShader(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getInfoLog(GLsizei bufSize, GLsizei * length, GLchar * infoLog) const {
        return ::gl::getShaderInfoLog(m_id, bufSize, length, infoLog);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    std::string getInfoLog(GLsizei bufSize) const {
        return ::gl::getShaderInfoLog(m_id, bufSize);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    std::string getInfoLog() const {
        return ::gl::getShaderInfoLog(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getSource(GLsizei bufSize, GLsizei * length, GLchar * source) const {
        return ::gl::getShaderSource(m_id, bufSize, length, source);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    std::string getSource(GLsizei bufSize) const {
        return ::gl::getShaderSource(m_id, bufSize);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void getiv(::gl::ShaderParameterName pname, GLint * params) const {
        return ::gl::getShaderiv(m_id, pname, params);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    GLint getiv(::gl::ShaderParameterName pname) const {
        return ::gl::getShaderiv(m_id, pname);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    GLboolean is() const {
        return ::gl::isShader(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 20
    void source(GLsizei count, const GLchar *const* string, const GLint * length) const {
        return ::gl::shaderSource(m_id, count, string, length);
    }
#endif
};

/**
 * @brief Object-style wrapper around an OpenGL Texture handle.
 * Exposes legacy (non-DSA) GL commands that take a Texture as
 * their first parameter as member methods, returning the strongly-typed
 * wrappers (UniformLocation, std::string, …) where available.
 */
class Texture {
    ::gl::Texture m_id;
public:
    Texture() = default;
    explicit Texture(::gl::Texture id) : m_id(id) {}
    ::gl::Texture id() const { return m_id; }
#if GLAZE_GL_VERSION >= 11
    GLboolean is() const {
        return ::gl::isTexture(m_id);
    }
#endif
};

/**
 * @brief Object-style wrapper around an OpenGL VertexArray handle.
 * Exposes legacy (non-DSA) GL commands that take a VertexArray as
 * their first parameter as member methods, returning the strongly-typed
 * wrappers (UniformLocation, std::string, …) where available.
 */
class VertexArray {
    ::gl::VertexArray m_id;
public:
    VertexArray() = default;
    explicit VertexArray(::gl::VertexArray id) : m_id(id) {}
    ::gl::VertexArray id() const { return m_id; }
#if GLAZE_GL_VERSION >= 30
    void bind() const {
        return ::gl::bindVertexArray(m_id);
    }
#endif
#if GLAZE_GL_VERSION >= 30
    GLboolean is() const {
        return ::gl::isVertexArray(m_id);
    }
#endif
};

} // namespace handle
} // namespace gl

// ── glaze::Traits specializations (legacy wrappers) ─────────────────────────
// Bridges the gl::handle::* wrapper classes into glaze::Unique / Shared
// / Weak. Coexists with the DSA and raw-handle traits already declared in
// gl.hpp; users pick the wrapper family at instantiation time.
namespace glaze {

#if GLAZE_GL_VERSION >= 15
template<> struct Traits<::gl::handle::Buffer> {
    static ::gl::handle::Buffer create() {
        return ::gl::handle::Buffer(::gl::genBuffer());
    }
    static void destroy(::gl::handle::Buffer& w) {
        ::gl::deleteBuffer(w.id());
    }
    static bool valid(const ::gl::handle::Buffer& w) {
        return static_cast<bool>(w.id());
    }
};
#endif

#if GLAZE_GL_VERSION >= 30
template<> struct Traits<::gl::handle::Framebuffer> {
    static ::gl::handle::Framebuffer create() {
        return ::gl::handle::Framebuffer(::gl::genFramebuffer());
    }
    static void destroy(::gl::handle::Framebuffer& w) {
        ::gl::deleteFramebuffer(w.id());
    }
    static bool valid(const ::gl::handle::Framebuffer& w) {
        return static_cast<bool>(w.id());
    }
};
#endif

#if GLAZE_GL_VERSION >= 20
template<> struct Traits<::gl::handle::Program> {
    static ::gl::handle::Program create() {
        return ::gl::handle::Program(::gl::createProgram());
    }
    static void destroy(::gl::handle::Program& w) {
        ::gl::deleteProgram(w.id());
    }
    static bool valid(const ::gl::handle::Program& w) {
        return static_cast<bool>(w.id());
    }
};
#endif

#if GLAZE_GL_VERSION >= 15
template<> struct Traits<::gl::handle::Query> {
    static ::gl::handle::Query create() {
        return ::gl::handle::Query(::gl::genQuerie());
    }
    static void destroy(::gl::handle::Query& w) {
        ::gl::deleteQuerie(w.id());
    }
    static bool valid(const ::gl::handle::Query& w) {
        return static_cast<bool>(w.id());
    }
};
#endif

#if GLAZE_GL_VERSION >= 30
template<> struct Traits<::gl::handle::Renderbuffer> {
    static ::gl::handle::Renderbuffer create() {
        return ::gl::handle::Renderbuffer(::gl::genRenderbuffer());
    }
    static void destroy(::gl::handle::Renderbuffer& w) {
        ::gl::deleteRenderbuffer(w.id());
    }
    static bool valid(const ::gl::handle::Renderbuffer& w) {
        return static_cast<bool>(w.id());
    }
};
#endif

#if GLAZE_GL_VERSION >= 33
template<> struct Traits<::gl::handle::Sampler> {
    static ::gl::handle::Sampler create() {
        return ::gl::handle::Sampler(::gl::genSampler());
    }
    static void destroy(::gl::handle::Sampler& w) {
        ::gl::deleteSampler(w.id());
    }
    static bool valid(const ::gl::handle::Sampler& w) {
        return static_cast<bool>(w.id());
    }
};
#endif

#if GLAZE_GL_VERSION >= 20
template<> struct Traits<::gl::handle::Shader> {
    static ::gl::handle::Shader create(::gl::ShaderType type) {
        return ::gl::handle::Shader(::gl::createShader(type));
    }
    static void destroy(::gl::handle::Shader& w) {
        ::gl::deleteShader(w.id());
    }
    static bool valid(const ::gl::handle::Shader& w) {
        return static_cast<bool>(w.id());
    }
};
#endif

#if GLAZE_GL_VERSION >= 11
template<> struct Traits<::gl::handle::Texture> {
    static ::gl::handle::Texture create() {
        return ::gl::handle::Texture(::gl::genTexture());
    }
    static void destroy(::gl::handle::Texture& w) {
        ::gl::deleteTexture(w.id());
    }
    static bool valid(const ::gl::handle::Texture& w) {
        return static_cast<bool>(w.id());
    }
};
#endif

#if GLAZE_GL_VERSION >= 30
template<> struct Traits<::gl::handle::VertexArray> {
    static ::gl::handle::VertexArray create() {
        return ::gl::handle::VertexArray(::gl::genVertexArray());
    }
    static void destroy(::gl::handle::VertexArray& w) {
        ::gl::deleteVertexArray(w.id());
    }
    static bool valid(const ::gl::handle::VertexArray& w) {
        return static_cast<bool>(w.id());
    }
};
#endif

} // namespace glaze

#endif
