from abc import ABC, abstractmethod
from datetime import datetime, timezone

import jinja2

from glaze.doc_parser import FunctionDoc
from glaze.model import Registry

_env = jinja2.Environment(
    loader=jinja2.PackageLoader("glaze", "templates"),
    trim_blocks=True,
    lstrip_blocks=True,
    keep_trailing_newline=True,
)


def _vendor_of(extension_name: str) -> str | None:
    """Extract the vendor token from an extension name.

    ``GL_ARB_buffer_storage`` → ``ARB``, ``GL_3DFX_multisample`` → ``3DFX``.
    Returns ``None`` if the name doesn't follow the ``GL_<VENDOR>_*`` pattern.
    """
    if not extension_name.startswith("GL_"):
        return None
    rest = extension_name[3:]
    if "_" not in rest:
        return None
    return rest.split("_", 1)[0].upper()


class Generator(ABC):
    """Abstract base for all language generators.

    Each generator receives a fully-parsed Registry and produces one or more
    output files keyed by their relative path.
    """

    def __init__(
        self,
        registry: Registry,
        doc_index: dict[str, FunctionDoc] | None = None,
        extension_vendors: list[str] | None = None,
        extension_names: list[str] | None = None,
    ):
        self.registry = registry
        self.doc_index: dict[str, FunctionDoc] = doc_index or {}
        self._extension_vendor_set: set[str] = {
            v.upper() for v in (extension_vendors or [])
        }
        self._extension_name_set: set[str] = set(extension_names or [])

    @abstractmethod
    def generate(self, api: str, version: str) -> dict[str, str]:
        """Generate output for the given API and version.

        Returns a dict mapping relative file paths to their string contents.
        Example: {"include/oglhpp/gl.h": "...", "src/gl.c": "..."}
        """
        ...

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable generator name (e.g., 'c', 'cpp')."""
        ...

    def _generation_header(self, api: str, version: str, lang: str) -> str:
        """Return a comment block indicating the file is auto-generated."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        return (
            f"Auto-generated by Glaze — DO NOT EDIT.\n"
            f"API: {api} {version} | Language: {lang} | Generated: {timestamp}"
        )

    def _build_command_version_map(self, api: str, version: str) -> dict[str, str]:
        """Map each command name to the earliest API version that required it."""
        features = self.registry.collect_features(api, version)
        cmd_version: dict[str, str] = {}
        for feature in features:
            for require in feature.require_list:
                for cmd_ref in require.commands:
                    if cmd_ref.name not in cmd_version:
                        cmd_version[cmd_ref.name] = feature.number
        return cmd_version

    def _collect_extension_emissions(self, api: str, version: str) -> list[dict]:
        """Return per-extension emission descriptors for the given API/ceiling.

        Only extensions matching the constructor-supplied ``extension_vendors``
        or ``extension_names`` filters are included.  If neither filter was set,
        an empty list is returned (extensions are opt-in).

        For each matched extension returns a dict carrying:

        - ``name``: the full Khronos extension name (e.g. ``GL_ARB_buffer_storage``).
        - ``short_name``: the name with the ``GL_`` prefix stripped, used in the
          C++ ``gl::exts::*`` namespace and as the suffix for build-time guards.
        - ``guard_macro``: ``GLAZE_GL_NO_EXT_<short_name>``.
        - ``flag_var``: ``GLAZE_EXT_<full_name>`` — the C ``int`` flag set at
          ``glazeLoadExtensions`` time.
        - ``khronos_define``: same as ``name`` (separate field for template
          clarity).
        - ``enums``: list of ``Enum`` objects this extension uniquely contributes
          (i.e. NOT already required by any core feature ≤ ``version``).
        - ``commands``: list of ``Command`` objects this extension uniquely
          contributes (same dedup rule).

        Extensions whose enums and commands are entirely covered by core are
        still returned — the consumer can still detect them at runtime via
        ``glazeHasExtension`` / ``gl::exts::<name>`` even when there's nothing
        new to declare. Extensions are returned in registry declaration order.
        """
        consolidated = self.registry.consolidate(api, version)
        extensions = self._filter_extensions(self.registry.extensions_for_api(api))
        emissions: list[dict] = []
        for ext in extensions:
            short_name = ext.name[3:] if ext.name.startswith("GL_") else ext.name
            enums: list = []
            commands: list = []
            seen_enum_names: set[str] = set()
            seen_command_names: set[str] = set()
            for require in ext.require_list:
                for enum_ref in require.enums:
                    if enum_ref.name in consolidated.enums:
                        continue
                    if enum_ref.name in seen_enum_names:
                        continue
                    enum = self.registry.enum_by_name.get(enum_ref.name)
                    if enum is None:
                        continue
                    enums.append(enum)
                    seen_enum_names.add(enum_ref.name)
                for cmd_ref in require.commands:
                    if cmd_ref.name in consolidated.commands:
                        continue
                    if cmd_ref.name in seen_command_names:
                        continue
                    command = self.registry.command_by_name.get(cmd_ref.name)
                    if command is None:
                        continue
                    commands.append(command)
                    seen_command_names.add(cmd_ref.name)
            emissions.append(
                {
                    "name": ext.name,
                    "short_name": short_name,
                    "guard_macro": f"GLAZE_GL_NO_EXT_{short_name}",
                    "flag_var": f"GLAZE_EXT_{ext.name}",
                    "khronos_define": ext.name,
                    "enums": enums,
                    "commands": commands,
                }
            )
        return emissions

    def _filter_extensions(self, extensions: list) -> list:
        """Filter extensions by the configured vendor and name sets.

        Returns only extensions whose vendor matches ``_extension_vendor_set``
        or whose full name is in ``_extension_name_set``.  When both sets are
        empty, returns an empty list (opt-in default).
        """
        if not self._extension_vendor_set and not self._extension_name_set:
            return []
        result = []
        for ext in extensions:
            if ext.name in self._extension_name_set:
                result.append(ext)
            elif _vendor_of(ext.name) in self._extension_vendor_set:
                result.append(ext)
        return result

    def validate_extension_filters(self, api: str) -> list[str]:
        """Check that every requested vendor/extension exists for ``api``.

        Returns a list of error messages (empty if everything is valid).
        """
        extensions = self.registry.extensions_for_api(api)
        known_vendors: set[str] = set()
        known_names: set[str] = set()
        for ext in extensions:
            known_names.add(ext.name)
            vendor = _vendor_of(ext.name)
            if vendor:
                known_vendors.add(vendor)

        errors: list[str] = []
        for v in sorted(self._extension_vendor_set):
            if v not in known_vendors:
                errors.append(
                    f"unknown extension vendor '{v}' for api '{api}'. "
                    f"Known vendors: {', '.join(sorted(known_vendors))}"
                )
        for n in sorted(self._extension_name_set):
            if n not in known_names:
                errors.append(f"unknown extension '{n}' for api '{api}'.")
        return errors

    def _check_api_version(self, api: str, version: str) -> None:
        """Validate that the given API and version are available."""
        available = self.registry.available_apis()
        if api not in available:
            raise ValueError(f"API '{api}' not found. Available: {list(available.keys())}")
        if version not in available[api]:
            raise ValueError(
                f"Version '{version}' not found for '{api}'. Available: {available[api]}"
            )

    def _render_template(self, template_path: str, context: dict) -> str:
        """Render a Jinja2 template from glaze/templates/ with the given context."""
        template = _env.get_template(template_path)
        result: str = template.render(**context)
        return result

    def _read_static_template(self, path: str) -> str:
        """Read a non-templated source file from glaze/templates/ verbatim.

        Used for static assets (like the API-agnostic raii.hpp) that should be
        shipped alongside generated headers without going through Jinja.
        """
        source, _filename, _uptodate = _env.loader.get_source(_env, path)
        return source
