from abc import ABC, abstractmethod
from datetime import datetime, timezone

import jinja2

from glaze.doc_parser import FunctionDoc
from glaze.model import Registry

_env = jinja2.Environment(
    loader=jinja2.PackageLoader("glaze", "templates"),
    trim_blocks=True,
    lstrip_blocks=True,
    keep_trailing_newline=True,
)


class Generator(ABC):
    """Abstract base for all language generators.

    Each generator receives a fully-parsed Registry and produces one or more
    output files keyed by their relative path.
    """

    def __init__(self, registry: Registry, doc_index: dict[str, FunctionDoc] | None = None):
        self.registry = registry
        self.doc_index: dict[str, FunctionDoc] = doc_index or {}

    @abstractmethod
    def generate(self, api: str, version: str) -> dict[str, str]:
        """Generate output for the given API and version.

        Returns a dict mapping relative file paths to their string contents.
        Example: {"include/oglhpp/gl.h": "...", "src/gl.c": "..."}
        """
        ...

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable generator name (e.g., 'c', 'cpp')."""
        ...

    def _generation_header(self, api: str, version: str, lang: str) -> str:
        """Return a comment block indicating the file is auto-generated."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        return (
            f"Auto-generated by Glaze — DO NOT EDIT.\n"
            f"API: {api} {version} | Language: {lang} | Generated: {timestamp}"
        )

    def _build_command_version_map(self, api: str, version: str) -> dict[str, str]:
        """Map each command name to the earliest API version that required it."""
        features = self.registry.collect_features(api, version)
        cmd_version: dict[str, str] = {}
        for feature in features:
            for require in feature.require_list:
                for cmd_ref in require.commands:
                    if cmd_ref.name not in cmd_version:
                        cmd_version[cmd_ref.name] = feature.number
        return cmd_version

    def _check_api_version(self, api: str, version: str) -> None:
        """Validate that the given API and version are available."""
        available = self.registry.available_apis()
        if api not in available:
            raise ValueError(f"API '{api}' not found. Available: {list(available.keys())}")
        if version not in available[api]:
            raise ValueError(
                f"Version '{version}' not found for '{api}'. Available: {available[api]}"
            )

    def _render_template(self, template_path: str, context: dict) -> str:
        """Render a Jinja2 template from glaze/templates/ with the given context."""
        template = _env.get_template(template_path)
        result: str = template.render(**context)
        return result
