#!/bin/bash

# Process toolchain
TOOLCHAIN_GCC="gcc"
TOOLCHAIN_CLANG="clang"
TOOLCHAIN=$1
if [ $TOOLCHAIN != $TOOLCHAIN_GCC ] && [ $TOOLCHAIN != $TOOLCHAIN_CLANG ]
then
    echo "Supplied toolchain \"$TOOLCHAIN\" is unknown."
    echo "  $TOOLCHAIN_GCC"
    echo "  $TOOLCHAIN_CLANG"
    echo "Are the only known options"
    exit 1
fi

if [ $TOOLCHAIN == $TOOLCHAIN_GCC ]
then
    export CC=gcc 
    export CXX=g++
fi

if [ $TOOLCHAIN == $TOOLCHAIN_CLANG ]
then
    export CC=clang
    export CXX=clang++
fi


# Process build type
BUILD_TYPE_DEBUG="debug"
BUILD_TYPE_RELEASE="release"
BUILD_TYPE=$2
if [ $BUILD_TYPE != $BUILD_TYPE_DEBUG ] && [ $BUILD_TYPE != $BUILD_TYPE_RELEASE ]
then
    echo "Supplied build type \"$BUILD_TYPE\" is unknown"
    echo "  $BUILD_TYPE_DEBUG"
    echo "  $BUILD_TYPE_RELEASE"
    echo "Are the only known options."
    exit 1
fi

if [ $BUILD_TYPE == $BUILD_TYPE_DEBUG ]
then
    CMAKE_BUILD_TYPE="Debug"
fi

if [ $BUILD_TYPE == $BUILD_TYPE_RELEASE ]
then
    CMAKE_BUILD_TYPE="Release"
fi

SOURCE_PREFIX=dependencies
BUILD_PREFIX=dependencies/.build
INSTALL_PREFIX=local


# build catch
# header-only-lib
CATCH2_BUILD_DIR="$BUILD_PREFIX/Catch2/$TOOLCHAIN"
CATCH2_SOURCE_DIR="$SOURCE_PREFIX/Catch2"
CATCH2_INSTALL_PREFIX="$INSTALL_PREFIX/Catch2/$TOOLCHAIN"

cmake -B$CATCH2_BUILD_DIR -S$CATCH2_SOURCE_DIR -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$CATCH2_INSTALL_PREFIX -DCATCH_BUILD_TESTING=OFF -DCATCH_INSTALL_DOCS=OFF
cmake --build $CATCH2_BUILD_DIR
cmake --install $CATCH2_BUILD_DIR

# build glades2
GLADES_BUILD_DIR="$BUILD_PREFIX/glades2/$TOOLCHAIN/$BUILD_TYPE"
GLADES_SOURCE_DIR="$SOURCE_PREFIX/glades2"
GLADES_INSTALL_PREFIX="$INSTALL_PREFIX/glades2/$TOOLCHAIN"

cmake -B$GLADES_BUILD_DIR -S$GLADES_SOURCE_DIR -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$GLADES_INSTALL_PREFIX
cmake --build $GLADES_BUILD_DIR
cmake --install $GLADES_BUILD_DIR

# build glfw
GLFW3_BUILD_DIR="$BUILD_PREFIX/glfw/$TOOLCHAIN/$BUILD_TYPE"
GLFW3_SOURCE_DIR="$SOURCE_PREFIX/glfw"
GLFW3_INSTALL_PREFIX="$INSTALL_PREFIX/glfw/$TOOLCHAIN"

cmake -B$GLFW3_BUILD_DIR -S$GLFW3_SOURCE_DIR -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$GLFW3_INSTALL_PREFIX -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF
cmake --build $GLFW3_BUILD_DIR
cmake --install $GLFW3_BUILD_DIR

# build glbinding
GLBINDING_BUILD_DIR="$BUILD_PREFIX/glbinding/$TOOLCHAIN/$BUILD_TYPE"
GLBINDING_SOURCE_DIR="$SOURCE_PREFIX/glbinding"
GLBINDING_INSTALL_PREFIX="$INSTALL_PREFIX/glbinding/$TOOLCHAIN"

cmake -B$GLBINDING_BUILD_DIR -S$GLBINDING_SOURCE_DIR -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$GLBINDING_INSTALL_PREFIX -DOPTION_BUILD_EXAMPLES=OFF -DOPTION_BUILD_TOOLS=OFF -DBUILD_SHARED_LIBS=OFF
cmake --build $GLBINDING_BUILD_DIR
cmake --install $GLBINDING_BUILD_DIR
