name: CI macOS
on: [push]
jobs:
  build-universal-appleclang:
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: brew install vulkan-headers

      - name: Install Dependencies
        run: |
          sh Xenobuild installdeps clang debug
          sh Xenobuild installdeps clang release

      - name: Configure [Debug]
        run: sh Xenobuild configure clang debug

      - name: Build [Debug]
        run: cmake --build build/clang/debug

      - name: Configure [Release]
        run: sh Xenobuild configure clang release

      - name: Build [Release]
        run: cmake --build build/clang/release
