name: CI macOS
on: [push]
jobs:
  ci-macos-11-universal-clang-debug:
    runs-on: macos-11
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: brew install vulkan-headers

      - name: Install Dependencies
        run: sh Xenobuild installdeps clang debug

      - name: Configure
        run: sh Xenobuild configure clang debug

      - name: Build
        run: cmake --build build/clang/debug

      - name: Run Unit Tests
        run: cmake --build build/clang/debug --target test

      - name: Generate Unit Test Coverage
        run: | 
          sh Xenobuild configure clang coverage 
          sh Xenobuild coverage clang coverage
          

          
  ci-macos-11-universal-clang-release:
    runs-on: macos-11
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: brew install vulkan-headers

      - name: Install Dependencies
        run: sh Xenobuild installdeps clang release

      - name: Configure
        run: sh Xenobuild configure clang release

      - name: Build
        run: cmake --build build/clang/release

      - name: Run Unit Tests
        run: cmake --build build/clang/release --target test
