name: CI Ubuntu
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Conan
        uses: conan-io/setup-conan@v1

      - name: Install Conan dependencies with lockfile
        #run: conan install . --lockfile=conan.lock --lockfile-partial --lockfile-out=conan.lock --build=missing
        run: conan install . --build=missing

      - name: Configure
        run: cmake --preset conan-release

      - name: Build
        run: cmake --build --preset conan-release
