name: CI Pipeline
on: [push]
jobs:
  formatting-check:
    name: check format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'src/engine'
            exclude: '(dependencies)'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.10.1
      continue-on-error: true
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}

  build:
    strategy:
      fail-fast: false
      matrix: 
        cmake-build-type: [Debug, Release]
        config:
        - os: ubuntu-latest
          generator: Unix Makefiles
          prologue: ""

        - os: macos-latest
          generator: Unix Makefiles
          prologue: ""

        - os: windows-latest
          generator: NMake Makefiles
          prologue: Invoke-Environment "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        run: |
          ${{ matrix.config.prologue }}
          cmake -G "${{matrix.config.generator}}" -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }} -DXE_DEV_WARNINGS_AS_ERRORS=ON -DXE_DEV_UNIT_TEST=ON 

      - name: Build
        run: cmake --build build --parallel 4

      - name: Run unit tests
        run: cd build && ctest --output-on-failure

  lint:
    needs: build
    strategy:
      fail-fast: false
      matrix: 
        cmake-build-type: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
      - name: Install clang-tidy
        run: sudo apt-get update && sudo apt-get install clang-tidy

      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        run: CC=clang CXX=clang++ cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }} -DXE_DEV_WARNINGS_AS_ERRORS=OFF -DXE_DEV_UNIT_TEST=OFF -DXE_DEV_LINT_CLANG_TIDY=ON

      - name: Build
        run: cmake --build build --parallel 4

  coverage:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix: 
        cmake-build-type: [Debug, Release]
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        run: CC=clang CXX=clang++ cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }} -DXE_DEV_WARNINGS_AS_ERRORS=OFF -DXE_DEV_UNIT_TEST=ON -DXE_DEV_INSTRUMENT_COVERAGE=ON

      - name: Build
        run: cmake --build build --parallel 4

      - name: Run unit tests
        run: cd build && ctest --output-on-failure

      - name: Check Coverage > 80%
        run: ./xbcli coverage

  asan:
    runs-on: ubuntu-latest
    needs:
      - coverage
      - lint
    steps:
      - name: check
        run: echo "check"

  ubsan:
    runs-on: ubuntu-latest
    needs:
      - coverage
      - lint
    steps:
      - name: check
        run: echo "check"

  msan:
    runs-on: ubuntu-latest
    needs:
      - coverage
      - lint
    steps:
      - name: check
        run: echo "check"
