name: CI Pipeline
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Format check
        run: echo "Format check"

  build:
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
        cmake-build-type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }} -DXE_DEV_WARNINGS_AS_ERRORS=OFF -DXE_DEV_UNIT_TEST=ON 

      - name: Build
        run: cmake --build build --parallel 4

      - name: Run unit tests
        run: cd build && ctest --output-on-failure
