name: Continous Integration
on: [push]
jobs:
  ci-ubuntu-latest-x86_64-gcc-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: sudo apt install xorg-dev 

      - name: Install Dependencies
        run: sh Xenobuild installdeps gcc debug

      - name: Configure
        run: sh Xenobuild configure gcc debug

      - name: Build
        run: cmake --build build/gcc/debug

      - name: Run Unit Tests
        run: cmake --build build/gcc/debug --target test

  ci-ubuntu-latest-x86_64-gcc-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: sudo apt install xorg-dev 

      - name: Install Dependencies
        run: sh Xenobuild installdeps gcc release

      - name: Configure
        run: sh Xenobuild configure gcc release

      - name: Build
        run: cmake --build build/gcc/release

      - name: Run Unit Tests
        run: cmake --build build/gcc/release --target test


  ci-ubuntu-latest-x86_64-clang-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: sudo apt install xorg-dev

      - name: Install Dependencies
        run: sh Xenobuild installdeps clang debug

      - name: Configure
        run: sh Xenobuild configure clang debug

      - name: Build
        run: cmake --build build/clang/debug

      - name: Run Unit Tests
        run: cmake --build build/clang/debug --target test


  ci-ubuntu-latest-x86_64-clang-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: sudo apt install xorg-dev

      - name: Install Dependencies
        run: sh Xenobuild installdeps clang release

      - name: Configure
        run: sh Xenobuild configure clang release

      - name: Build
        run: cmake --build build/clang/release

      - name: Run Unit Tests
        run: cmake --build build/clang/release --target test


  ci-macos-11-x86_64-clang-debug:
    runs-on: macos-11
    env:
      CC: clang
      CXX: clang++
      CFLAGS: -Wall --analyze
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: brew install vulkan-headers

      - name: Install Dependencies
        run: sh Xenobuild installdeps clang debug

      - name: Configure
        run: sh Xenobuild configure clang debug

      - name: Build
        run: cmake --build build/clang/debug

      - name: Run Unit Tests
        run: cmake --build build/clang/debug --target test


  ci-macos-11-x86_64-clang-release:
    runs-on: macos-11
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: brew install vulkan-headers

      - name: Install Dependencies
        run: sh Xenobuild installdeps clang release

      - name: Configure
        run: sh Xenobuild configure clang release

      - name: Build
        run: cmake --build build/clang/release

      - name: Run Unit Tests
        run: cmake --build build/clang/release --target test


  ci-windows-latest-x86_64-vc-debug:
    runs-on: windows-latest
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Dependencies
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          PowerShell .\Xenobuild -mode installdeps -toolchain vc -buildType debug

      - name: Configure
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          PowerShell .\Xenobuild -mode configure -toolchain vc -buildType debug

      - name: Build
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build build/vc/debug

      - name: Run Unit Tests
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build build/vc/debug --target test

  ci-windows-latest-x86_64-vc-release:
    runs-on: windows-latest
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Dependencies
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          PowerShell .\Xenobuild -mode installdeps -toolchain vc -buildType release

      - name: Configure
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          PowerShell .\Xenobuild -mode configure -toolchain vc -buildType release

      - name: Build
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build build/vc/release

      - name: Run Unit Tests
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build build/vc/release --target test
