name: Ubuntu CI
on: [push]
jobs:
  Ubuntu-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code and Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: (gcc) Configure a Debug Build
        run: mkdir -p build/gcc/debug && cmake -B build/gcc/debug -DCMAKE_BUILD_TYPE=Debug

      - name: (gcc) Building Debug Configuration
        run: cmake --build build/gcc/debug

      - name: (clang) Configure a Debug Build
        run: mkdir -p build/clang/debug && CC=clang CXX=clang++ cmake -B build/gcc/debug -DCMAKE_BUILD_TYPE=Debug

      - name: (clang) Building Debug Configuration
        run: cmake --build build/clang/debug
